#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HTML_PATH = ROOT / "html"
TEMPLATE_PATH = HTML_PATH / "index.template.html"
PAGES_PATH = HTML_PATH / "pages.json"


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def build_nav(languages: list[dict], domains: list[dict], current_key: str) -> str:
    groups = []
    for lang in languages:
        items = []
        for domain in domains:
            key = f"{lang['code']}-{domain['id']}"
            is_active = key == current_key
            classes = "nav-link is-active" if is_active else "nav-link"
            aria = " aria-current=\"page\"" if is_active else ""
            href = f"index-{key}.html"
            items.append(f"<a class=\"{classes}\" href=\"{href}\"{aria}>{domain['label']}</a>")
        group = (
            "<div class=\"nav-group\">"
            f"<span class=\"nav-group-label\">{lang['label']}</span>"
            "<span class=\"nav-sep\">(</span>"
            + " / ".join(items)
            + "<span class=\"nav-sep\">)</span>"
            "</div>"
        )
        groups.append(group)
    return "\n        ".join(groups)


def render(template: str, values: dict) -> str:
    result = template
    for key, value in values.items():
        result = result.replace(f"{{{{{key}}}}}", value)
    return result


def main() -> None:
    pages = load_json(PAGES_PATH)
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    generated_note = "Generated by scripts/generate-pages.py. Do not edit directly."

    languages = pages["languages"]
    domains = pages["domains"]
    default_lang = pages["default"]["lang"]
    default_domain = pages["default"]["domain"]

    for lang in languages:
        for domain in domains:
            key = f"{lang['code']}-{domain['id']}"
            nav = build_nav(languages, domains, key)
            domain_label = domain["label"]
            domain_label_lower = domain_label.lower()
            noun = domain["noun"]
            noun_cap = noun[:1].upper() + noun[1:]

            html = render(
                template,
                {
                    "LANG_CODE": lang["code"],
                    "LANG_LABEL": lang["label"],
                    "DOMAIN_LABEL": domain_label,
                    "DOMAIN_LABEL_LOWER": domain_label_lower,
                    "DOMAIN_NOUN": noun,
                    "DOMAIN_NOUN_CAP": noun_cap,
                    "NAV": nav,
                    "CONFIG_JS": f"config-{lang['code']}-{domain['id']}.js",
                    "GENERATED_COMMENT": f"<!-- {generated_note} -->",
                },
            )

            output_path = HTML_PATH / f"index-{lang['code']}-{domain['id']}.html"
            output_path.write_text(html, encoding="utf-8")

            config_path = HTML_PATH / f"config-{lang['code']}-{domain['id']}.js"
            tax_tsv = f"tax-{lang['code']}-{domain['id']}.tsv"
            page_tsv = f"page-{lang['code']}-{domain['id']}.tsv"
            config_body = (
                f"// {generated_note}\n"
                "window.APP_CONFIG = {\n"
                f"  WIKI_PAGE: \"{lang['wiki']}\",\n"
                f"  WIKI_FILE: \"{lang['file']}\",\n"
                f"  TAX_TSV: \"{tax_tsv}\",\n"
                f"  PAGE_TSV: \"{page_tsv}\",\n"
                f"  LANGUAGE: \"{lang['label']}\",\n"
                "};\n"
            )
            config_path.write_text(config_body, encoding="utf-8")

    default_page = HTML_PATH / f"index-{default_lang}-{default_domain}.html"
    if default_page.exists():
        (HTML_PATH / "index.html").write_text(default_page.read_text(encoding="utf-8"), encoding="utf-8")


if __name__ == "__main__":
    main()
